### ISSUE TITLE
show and editing tenant level limits

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#254]
blocked by PlaceOS/staff-api#161

The limits will be exposed as a hash: String (limit name) => Int (limit count)

i.e.

```yaml
{
  "desk": 2,
  "parking": 1
}
```
