### ISSUE TITLE
Fix Staff API tenant form + add new options

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#267]
I've noticed that the conference_type key is in the wrong place:

```yaml
{
  "domain": "localhost",
  "name": "Example",
  "platform": "google",
  "conference_type": "Teams", # this should be part of the credentials
  "booking_limits": {},
  "credentials": {
    "issuer": "steve@vontaka.ch",
    "signing_key": "some key",
    "scopes": "public",
    "domain": "localhost",
    "sub": "me@place.tech",
    "user_agent": "PlaceOS"
  }
}
```

The request should look like this:

```json
{
  "domain": "localhost",
  "name": "Example",
  "platform": "google",
  "booking_limits": {},
  "credentials": {
    "issuer": "steve@vontaka.ch",
    "signing_key": "some key",
    "scopes": "public",
    "domain": "localhost",
    "sub": "me@place.tech",
    "user_agent": "PlaceOS",
    "conference_type": "Teams"
  }
}
```

You can see the valid Params here: https://github.com/PlaceOS/staff-api/blob/master/src/models/tenant.cr#L19

In terms of new options, we need a checkbox: `delegated` that changes what fields are shown for both office and google.
This is an example of a valid delegated office365 config:

```json
{
    "domain": "placeos-dev.aca.im",
    "name": "Test Delegation",
    "platform": "office365",
    "delegated": true,
    "booking_limits": {},
    "credentials": {
        "conference_type": "Teams"
    }
}
```

basically, hide these fields (Client ID, Client Secret, Tenant)
<img width="138" alt="image" src="https://user-images.githubusercontent.com/368013/167982388-0c4069c6-446e-4cc7-b262-52ce2b9e15c0.png">

Example delegated Google payload:

```json
{
    "domain": "placeos-dev.aca.im",
    "name": "Test Delegation",
    "platform": "office365",
    "delegated": true,
    "booking_limits": {},
    "credentials": {
        "conference_type": "Teams",
        "domain": "place.technology",
        "user_agent": "PlaceOS",
    }
}
```

i.e. when `delegated: true` remove the fields: 

* Service Account Email
* Scopes
* Private Key
* Service User
